#!/bin/bash

# Copyright (c) 2022 FEROX YT EIRL, www.ferox.yt <devops@ferox.yt>
# Copyright (c) 2022 Jérémy WALTHER <jeremy.walther@golflima.net>
# See <https://github.com/frxyt/docker-crypt> for details.

set -e;

if [[ "${FRX_DEBUG}" == "1" ]]; then
    set -x;
fi

openssl aes-256-cbc -d -kfile ${2:-/work/password} -pbkdf2 -iter 10 -in encrypted -out compressed.tar.gz
tar -xvzf compressed.tar.gz -C /
rm -f compressed.tar.gz